spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 1995
    url: jdbc:mysql://localhost:3306/mannu_db
    username: root
  jpa:
    show-sql: true

    hibernate:
      ddl-auto: none
      
server:
  port: 9093   
